export type TEmoji = {
  [key: string]: string;
};

export const EmojiData: TEmoji = {
  "::angry-horn::": "/emoji/angry-horn.png",
  "::big-cry::": "/emoji/big-cry.png",
  "::big-smile::": "/emoji/big-smile.png",
  "::blue-heart::": "/emoji/blue-heart.png",
  "::vomit::": "/emoji/vomit.png",
  "::cry-eye::": "/emoji/cry-eye.png",
  "::discuss-face::": "/emoji/discuss-face.png",
  "::dolphin::": "/emoji/dolphin.png",
  "::dot-face::": "/emoji/dot-face.png",
  "::fu::": "/emoji/fu.png",
  "::glass::": "/emoji/glass.png",
  "::goblin::": "/emoji/goblin.png",
  "::finger-quiet::": "/emoji/finger-quiet.png",
  "::herong-face::": "/emoji/herong-face.png",
  "::hi::": "/emoji/hi.png",
  "::hot-face::": "/emoji/hot-face.png",
  "::quiet::": "/emoji/quiet.png",
  "::scream::": "/emoji/scream.png",
  "::hand-quiet::": "/emoji/hand-quiet.png",
  "::sigh::": "/emoji/sigh.png",
  "::sunglass::": "/emoji/sunglass.png",
  "::surprised::": "/emoji/surprised.png",
  "::sweat-face::": "/emoji/sweat-face.png",
  "::think-face::": "/emoji/think-face.png",
  "::tired-face::": "/emoji/tired-face.png",
  "::tree::": "/emoji/tree.png",
  "::tyrano::": " /emoji/tyrano.png",
  "::worry-face::": " /emoji/worry-face.png",
  "::wtf::": " /emoji/wtf.png",
  "::zip-mouse::": " /emoji/zip-mouse.png",
};
